name: Generate Documentation

on:
  pull_request

jobs:
  generate:
    if: github.repository == 'zeek/zeek-docs'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Fetch Dependencies
        run: sudo pip3 install --break-system-packages -r requirements.txt
      - name: Generate Docs
        run: make SPHINXOPTS="-W --keep-going"
